### ISSUE TITLE
Mot de passe admin

### ISSUE THREAD

**Issue by axelos** [kd2org/paheko-nextcloud#1]
Bonjour,

Nous testons actuellement le module implémenté dans Nextcloud, lors de la demande de réinitialisation de la base, est demandé un mot de passe.

Savez-vous quel est le mot de passe par défaut pour le compte admin ?

Bien cordialement, Axel.

**Comment by bohwaz** [comment]
Il n'y a pas de mot de passe, il n'est donc pas possible de remettre à zéro la base de données.

Merci du retour, je vais cacher cette fonctionnalité pour ce cas-là.
