### ISSUE TITLE
Impossible d'ajouter un membre à une activité

### ISSUE THREAD

**Issue by Jean-Pierre-Aublanc** [kd2org/paheko-nextcloud#2]
Bonjour,

Quand j'ajoute un membre à une activité (exemple, cotisation annuelle), et sans forcément le relier à la comptabilité, le message d'erreur Nextcloud ci-dessous s'affiche : 

"_Erreur interne du serveur
Le serveur est incapable d'exécuter votre requête.
Si cela se reproduit, veuillez envoyer les détails techniques ci-dessous à l'administrateur du serveur.
Le fichier journal du serveur peut fournir plus de renseignements._"

Version Paheko utilisée : 1.3.11

Cdt

JPA

**Comment by bohwaz** [comment]
Je ne fait pas de support sur ce projet qui n'est qu'expérimental. Merci de tester sur Paheko "normal" hors nextcloud.
